name: I'm living all alone because

on:
  push:
  workflow_dispatch:
jobs:
  build:
    name: Keep running back, coming back for more
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Build!
        run: |
          set -o pipefail

          xcodebuild \
            -project FuckXter.xcodeproj \
            -scheme FuckXter \
            -configuration Debug \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGNING_ALLOWED=NO \
            clean build
          
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData \
            -path "*/Build/Products/Debug-iphonesimulator/FuckXter.app" \
            -print -quit)
          
          mv -R "$APP_PATH" ./fuckxter.app

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: v0.0.1
          files: ./fuckxter.app
          body: |
            # 📝 Release Notes
            - Fixes and improvements